name: Basic checks
on:
  pull_request:
  push:
    branches:
    - master
jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check consistency of files in Makefiles
      run: dev/tools/check-make-sync.sh
    - name: Check for duplicate files
      run: dev/tools/check-duplicate-files.sh
    - name: Lint
      run: dev/lint-repository.sh
